name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocessing/parse-interplanetaryone-data.ts
  workflow_dispatch: {} # Required even though this is currently empty
  schedule:
    - cron: '0 0 1 * *' # Run this workflow every month on the first day of the month

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data (InterPlanetary One - Verifiers)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.filplus.d.interplanetary.one/public/api/getVerifiers
          axios_config: axios_config.json
          downloaded_filename: ./data/raw/interplanetaryone-verifiers.json
          postprocess: ./postprocessing/parse-interplanetaryone-data.ts
      - name: Fetch data (FilPlus Dev - Issues)
        uses: githubocto/flat@v3
        with:
          http_url: https://filplus.dev/api/issues
          downloaded_filename: ./data/raw/filplus-issues.json
      - name: Fetch data (filecoin-project/notary-governance - Issues)
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}; deno run -A --unstable --no-check ./postprocessing/fetch-notary-governance-issues.ts
