name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocessing/**.ts
  workflow_dispatch: {} # Required even though this is currently empty
  schedule:
    - cron: "0 0 1 * *" # Run this workflow every month on the first day of the month

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data (InterPlanetary One - Verifiers)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.filplus.d.interplanetary.one/public/api/getVerifiers
          axios_config: axios_config.json
          downloaded_filename: ./data/raw/interplanetaryone-verifiers.json
          # postprocess: ./postprocessing/parse-interplanetaryone-data.ts
      - name: Fetch data (InterPlanetary One - Verified Clients)
        uses: githubocto/flat@v3
        with:
          http_url: https://api.filplus.d.interplanetary.one/public/api/getVerifiedClients
          axios_config: axios_config.json
          downloaded_filename: ./data/raw/interplanetaryone-verified-clients.json
          # postprocess: ./postprocessing/parse-interplanetaryone-data.ts
      # - name: Fetch data (FilPlus Dev - Issues)
      #   uses: githubocto/flat@v3
      #   with:
      #     http_url: https://filplus.dev/api/issues
      #     downloaded_filename: ./data/raw/filplus-issues.json
      - name: Fetch data (filecoin-project/notary-governance - Issues)
        uses: githubocto/flat@v3
        with:
          http_url: https://empty-object.deno.dev
          downloaded_filename: ./data/raw/notary-governance-issues.json
          postprocess: ./postprocessing/fetch-notary-governance-issues.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DENO_FUTURE_CHECK: 1
      - name: Process data (filecoin-project/notary-governance - Issues)
        uses: githubocto/flat@v3
        with:
          http_url: https://empty-object.deno.dev
          downloaded_filename: ./data/processed/notary-governance-issues.json
          postprocess: ./postprocessing/parse-verifier-application-issue.ts
        env:
          DENO_FUTURE_CHECK: 1
      - name: Generate data (Address Mapping)
        uses: githubocto/flat@v3
        with:
          http_url: https://empty-object.deno.dev
          downloaded_filename: ./data/generated/address-mapping.json
          postprocess: ./postprocessing/generate-address-mapping.ts
        env:
          DENO_FUTURE_CHECK: 1
      - name: Generate data (Verifiers)
        uses: githubocto/flat@v3
        with:
          http_url: https://empty-object.deno.dev
          downloaded_filename: ./data/generated/verifiers.json
          postprocess: ./postprocessing/generate-verifiers-data.ts
        env:
          DENO_FUTURE_CHECK: 1
